<?php

/**
 * Implements hook_bean_types_api_info().
 */
function bean_focus_on_bean_types_api_info(){
  return array('api' => 4);
}

/**
 * Implements hook_bean_types().
 */
function bean_focus_on_bean_types() {
  $plugins = array();
  $plugins_path = drupal_get_path('module', 'bean_focus_on').'/plugins';
  $plugins['focus_on'] = array(
    'label' => t('Focus ON block'),
    'description' => t('Focus on module get the content type as Focus ON for test use article'),
    'handler' => array(
      'class' => 'FocusOnContentType',
      'parent' => 'bean',
    ),
    'path' => $plugins_path,
    'file' => 'FocusOnContentType.class.php',
  );
  return $plugins;
}

/**
 * Implements hook_theme().
 */
function bean_focus_on_theme() {
  $items = [];
  $items['bean_focus_on_settings'] = [
    'arguments' => [
      'records_shown' => NULL,
    ],
    'file' => 'bean_focus_on.theme.inc',
  ];
  $items['focusOnMoreLink'] = [
    'arguments' => [
      'text' => NULL,
      'path' => NULL,
    ],
    'file' => 'bean_focus_on.theme.inc'
  ];
  return $items;
}

function bean_custom_content_display_clear_cache(&$form){
  cache_clear_all('bean_custom_content_display', 'cache');

}
