<?php

/**
 * Implements hook_bean_types_api_info().
 */
function bean_block_bean_types_api_info(){
  return array('api' => 4);
}

/**
 * Implements hook_bean_types().
 */
function bean_block_bean_types() {
  $plugins = array();
  $plugins_path = drupal_get_path('module', 'bean_block').'/plugins';
  $plugins['focus_on'] = array(
    'label' => t('Bean Block'),
    'description' => t('Content Type for bean_block'),
    'handler' => array(
      'class' => 'BeanBlockContentType',
      'parent' => 'bean',
    ),
    'path' => $plugins_path,
    'file' => 'BeanBlockContentType.class.php',
  );
  return $plugins;
}

/**
 * Implements hook_theme().
 */
function bean_block_theme() {
  $items = [];
  $items['bean_block_settings'] = [
    'arguments' => [
      'records_shown' => NULL,
    ],
    'file' => 'bean_block.theme.inc',
  ];
  $items['BeanBlockMoreLink'] = [
    'arguments' => [
      'text' => NULL,
      'path' => NULL,
    ],
    'file' => 'bean_block.theme.inc'
  ];
  return $items;
}

function bean_custom_content_display_clear_cache(&$form){
  cache_clear_all('bean_custom_content_display', 'cache');

}
