<?php
/**
 * @file
 * Focus on Block Plugin
 */

class FocusOnContentType extends BeanPlugin {

  /*
   * Decalare default bloc setting
   */
  public function values() {
    // add new array of setting to the $bean variable
    $custom_setting_value = array (
      'settings' => array(
        'node_view_mode' => FALSE,
        'records_shown' => FALSE,
      ),
      'more_link' => array(
        'text' => '',
        'path' => '',
      ),
    );
    return array_merge(parent::values(), $custom_setting_value); // TODO: Change the autogenerated stub
  }

  /*
   * Building extra setting for edit form
   */

  public function form($bean, $form, &$form_state) {
    dpm($bean);
    $form = array();
//    $form['#tree'] = TRUE;
    $form['settings'] = array(
      '#type' => 'fieldset',
      '#tree' => 1,
      '#title' => t('Output Form'),
    );
    // get the view mode, and setto custom variable $node_view_mode
    $node_view_mode = array();
    $entity_info =  entity_get_info();
    foreach ($entity_info['node']['view modes'] as $key => $value){
      // get the name of view mode and store in new var
      $node_view_mode[$key] = $value['label'];
    }
    //if the view is not set default to full
    if(!isset($bean->settings['node_view_mode'])){
      $default_node_view_mode = 'full';
    }
    else{
      $default_node_view_mode = $bean->settings['node_view_mode'];
    }

    //check for the size of node to render
    if(!$records_shown = $bean->settings['records_shown']){
      $records_shown = 5;
    }

    //create the form value
    $form['settings']['node_view_mode'] = array(
      '#type' => 'select',
      '#title' => t('Select View Mode'),
      '#options' => $node_view_mode,
      '#default_value' => $default_node_view_mode,
      '#required' => TRUE,
      '#multiple' => FALSE,
    );

    $form['settings']['records_shown'] = array(
      '#type' => 'textfield',
      '#title' => t('Enter the node to render'),
      '#size' => 5,
      '#default_value' => $records_shown,
    );

    $form['content_type_select'] = array(
      '#type'  => 'fieldset',
      '#tree' => 1,
      '#title' => t('select the Content type'),
    );
    $form['more_link'] = array(
      '#type' => 'fieldset',
      '#tree' => 1,
      '#title' => t('Add link to the bottom'),
    );
    $form['more_link']['text'] = array(
      '#type' => 'textfield',
      '#title' => t('Text to show att he bottom'),
      '#default_value' => $bean->more_link['text'],
    );
    $form['more_link']['path'] = array(
      '#type' => 'textfield',
      '#title' => t('URL to link with the text'),
      '#default_value' => $bean->more_link['path'],
    );

    return array_merge(parent::values(),$form);

    //  return array_merge(parent::values(), $custom_setting_value);
//    return parent::form($bean, $form, $form_state);
  }

  public function view($bean, $content, $view_mode = 'default', $langcode = NULL) {
    dpm($bean);
    $query = new EntityFieldQuery();
    $query
      ->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'article')
      ->propertyCondition('status', 1)
      ->propertyOrderBy('created', 'DESC')
      ->range(0, $bean->settings['records_shown']);
    $results = $query->execute();
   // dpm($content);
    if(empty($results)){
      $content['node'] = array();
    }
    else{
      foreach ($results['node'] as $node){
        $node = node_load($node->nid, $node->vid);
        $content['nodes'][$node->nid] = node_view($node,$bean->settings['node_view_mode']);
      }
    }
   // dpm($content);
    $content['more_link']['#markup'] = theme('focusOnMoreLink', array('text'=>$bean->more_link['text'],
                                                                            'path'=>$bean->more_link['path']));


//    $content['more_link']['#markup'] = theme('article_listing_more_link', array('text' => $bean->more_link['text'],
//                                                                                      'path' => $bean->more_link['path']));
//
    return $content;
//    return parent::view($bean, $content, $view_mode, $langcode);
  }
}

