<?php
/**
 * @file
 * Focus on Block Plugin
 */

class FocusOnContentType extends BeanPlugin {

  /*
   * Decalare default bloc setting
   */
  public function values() {
    // add new array of setting to the $bean variable
    $custom_setting_value = array (
      'settings' => array(
        'node_view_mode' => FALSE,
        'records_shown' => FALSE,
        'cache_duration' => '30',
      ),
      'more_link' => array(
        'text' => '',
        'path' => '',
      ),
      'content_type' => array(
        'type' => '',
      ),
    );
    return array_merge(parent::values(), $custom_setting_value); // TODO: Change the autogenerated stub
  }

  /*
   * Building extra setting for edit form
   */

  public function form($bean, $form, &$form_state) {
    //  dpm($bean);
    $form = array();
    //    $form['#tree'] = TRUE;
    $form['settings'] = array(
      '#type' => 'fieldset',
      '#tree' => 1,
      '#title' => t('Output Form'),
    );

    // check for the content type
//     original correct code
//     $type = $node->type;
//     $types = node_type_get_types();
//     $name = $types[$type]->name;
//     $description = $types[$type]->description

//    $node = menu_get_object();
//    dpm($node);
//    $type = $node;

    //$type = array();
    $list_of_content_type = array();
    $types = node_type_get_types();
    foreach ($types as $type ) {
      $list_of_content_type[$type->name] = $type->name;
    }
   // dpm($list_of_content_type);

    // get the view mode, and setto custom variable $node_view_mode
    $node_view_mode = array();
    $entity_info =  entity_get_info();
    foreach ($entity_info['node']['view modes'] as $key => $value){
      print_r("the key vale is ", $key);
      // get the name of view mode and store in new var
      $node_view_mode[$key] = $value['label'];
    }
    //if the view is not set default to full
    if(!isset($bean->settings['node_view_mode'])){
      $default_node_view_mode = 'full';
    }
    else{
      $default_node_view_mode = $bean->settings['node_view_mode'];
    }

    //check for the size of node to render
    if(!$records_shown = $bean->settings['records_shown']){
      $records_shown = 5;
    }

    //create the form value
    $form['settings']['node_view_mode'] = array(
      '#type' => 'select',
      '#title' => t('Select View Mode'),
      '#options' => $node_view_mode,
      '#default_value' => $default_node_view_mode,
      '#required' => TRUE,
      '#multiple' => FALSE,
    );

    $form['settings']['records_shown'] = array(
      '#type' => 'textfield',
      '#title' => t('Enter the node to render'),
      '#size' => 5,
      '#default_value' => $records_shown,
    );
    dpm($bean->settings['cache_duration']);
    $form['settings']['cache_duration'] = array(
      '#type' => 'textfield',
      '#title' => t('Cache Duration in Minutes'),
      '#size' => 5,
      '#default_value' => $bean->settings['cache_duration'],
      '#required' => TRUE,
    );


    $form['content_type'] = array(
      '#type'  => 'fieldset',
      '#tree' => 1,
      '#title' => t('select the Content type'),
    );
    $form['content_type']['type'] = array(
      '#type' => 'select',
      '#title' => t('Select the content type to display'),
      '#options' => $list_of_content_type,
      '#required' => TRUE,
      '#multiple' => TRUE,
    );
    $form['more_link'] = array(
      '#type' => 'fieldset',
      '#tree' => 1,
      '#title' => t('Add link to the bottom'),
    );
    $form['more_link']['text'] = array(
      '#type' => 'textfield',
      '#title' => t('Text to show att he bottom'),
      '#default_value' => $bean->more_link['text'],
    );
    $form['more_link']['path'] = array(
      '#type' => 'textfield',
      '#title' => t('URL to link with the text'),
      '#default_value' => $bean->more_link['path'],
    );

    $form['#submit'][] = 'bean_custom_content_display_clear_cache';

    return array_merge(parent::values(),$form);

    //  return array_merge(parent::values(), $custom_setting_value);
//    return parent::form($bean, $form, $form_state);
  }

  /**
   * @param $bean
   * @param $content
   * @param string $view_mode
   * @param null $langcode
   *
   * @return mixed
   * @throws \Exception
   */
  public function view($bean, $content, $view_mode = 'default', $langcode = NULL) {
    dpm($bean);
    dpm($bean->content_type['type']);

    if($cache = cache_get('bean_custom_content_display')){
      $results =  $cache->data;
      print_r('inside cache result page');
    }
    else {
      $query = new EntityFieldQuery();
      $query
        ->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', $bean->content_type['type'])
        ->propertyCondition('status', 1)
        ->propertyOrderBy('created', 'DESC')
        ->range(0, $bean->settings['records_shown']);
      $results = $query->execute();
      cache_set('bean_custom_content_display',$results,'cache',time()+60* $bean->settings['cache_duration']);
      print_r("call the db query ");
    }
   // dpm($content);
    if(empty($results)){
      $content['node'] = array();
    }
    else{
      foreach ($results['node'] as $node){
        $node = node_load($node->nid, $node->vid);
        $content['nodes'][$node->nid] = node_view($node,$bean->settings['node_view_mode']);
      }
    }
   // dpm($content);
    $content['more_link']['#markup'] = theme('focusOnMoreLink', array('text'=>$bean->more_link['text'],
                                                                            'path'=>$bean->more_link['path']));


//    $content['more_link']['#markup'] = theme('article_listing_more_link', array('text' => $bean->more_link['text'],
//                                                                                      'path' => $bean->more_link['path']));
//
//    cache_set('bean_tweets-' . $bean->settings['handle'], $tweets, 'cache', time() + 60 * $bean->settings['cache_duration']);

    return $content;
//    return parent::view($bean, $content, $view_mode, $langcode);
  }
}

